package com.example.guide;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.os.Bundle;

import com.example.guide.Adapter.FamousPlacesAdapter;
import com.example.guide.Model.FamousPlacesModel;

import java.util.ArrayList;
import java.util.List;

public class FamousPlacesActivity extends AppCompatActivity {

    RecyclerView recyclerView;
    FamousPlacesAdapter famousPlacesAdapter;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_famous_places);

        String state_name = getIntent().getStringExtra("state_name");
        List<FamousPlacesModel> famousPlacesModelList = new ArrayList<>();


        if (state_name.equals("Andhra Pradesh")) {
            famousPlacesModelList.add(new FamousPlacesModel("Araku Valley and Borra Caves", "The Borra Caves " +
                    "(also called Borra Guhalu) are located on the East Coast of India, in the Ananthagiri hills of the Araku Valley " +
                    "(with hill ranges' elevation varying from 800 to 1,300 m (2,600 to 4,300 ft)) of the Alluri Sitharama Raju district " +
                    "in Andhra Pradesh. The caves, one of the largest in the country, at an elevation of about 705 m (2,313 ft), " +
                    "distinctly exhibit a variety of speleothems ranging in size and irregularly shaped stalactites and stalagmites." +
                    "[1][2] The caves are basically karstic limestone structures extending to a depth of 80 m (260 ft), and are considered " +
                    "the deepest caves in India.[3][4]", "17.741037,83.315813"));


            famousPlacesModelList.add(new FamousPlacesModel("Lord Venkateswara Temple", "Sri Venkateswara Swami Vaari Temple is a Hindu temple situated in the hill town of Tirumala at Tirupati in Tirupati district of Andhra Pradesh, India. The Temple is dedicated to Venkateswara, a form of Vishnu, who is believed to have appeared on the earth to save mankind from trials and troubles of Kali Yuga. Hence the place has also got the name Kaliyuga Vaikuntha and the Lord here is referred to as Kaliyuga Prathyaksha Daivam. The temple is also known by other names like Tirumala Temple, Tirupati Temple and Tirupati Balaji Temple. Venkateswara is known by many other names: Balaji, Govinda, and Srinivasa.[3] The temple is run by Tirumala Tirupati Devasthanams (TTD), which is under control of Andhra Pradesh Government. The head of TTD is appointed by Andhra Pradesh Government. The revenue from this shrine is used by Andhra Pradesh government.[4][5]", ""));
            famousPlacesModelList.add(new FamousPlacesModel("NagarjunaKonda", "Nagarjunakonda (IAST: Nāgārjunikoṇḍa, meaning Nagarjuna Hill) is a historical town, now an island located near Nagarjuna Sagar in Palnadu district of the Indian state of Andhra Pradesh, near the state border with Telangana.[2][3] It is one of India's richest Buddhist sites, and now lies almost entirely under the lake created by the Nagarjuna Sagar Dam. With the construction of the dam, the archaeological relics at Nagarjunakonda were submerged, and had to be excavated and transferred to higher land, which has become an island.", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Amaravati", "Amaravati (/ɑːməˈrɑːvəti/) is the capital of the Indian state of Andhra Pradesh.[a] It is located on the banks of the river Krishna in Guntur district.\n" + "\n" +
                    "The Prime Minister of India, Narendra Modi laid the foundation stone at a ceremonial event in Uddandarayunipalem village on 22 October 2015.[9]\n" + "\n" +
                    "Dharanikota, the ancient city site nearby, was founded more than 2,200 years ago, serving as an ancient capital.[10] The Amaravati Stupa was an important Buddhist site of pilgrimage and holy learning. Under the British Raj, many ancient Buddhist sculptures were taken to other museums in India and Britain.\n" + "\n" +
                    "The office of the Chief Minister of Andhra Pradesh has operated from Velagapudi since April 2016. The Andhra Pradesh Legislature remained in Hyderabad until March 2017, when it was relocated to newly constructed interim legislative buildings in Velagapudi.[11][12]", ""));


        } else if (state_name.equals("Arunachal Pradesh")) {
            famousPlacesModelList.add(new FamousPlacesModel("Gekar Sinyi (Ganga lake)", "Ganga Lake or Geker Sinying is a lake in Itanagar, the capital of Arunachal Pradesh. It is one of the most popular places in Itanagar. People from all around visit this place as a recreation spot and for the picture perfect view of this lake. Because the lake is still with no connection with moving water bodies, its color is green. Many mythological rumors about the Ganga Lake and its color are heard still. This lake is also known as Gyakar Sinyi and it houses wonderful works of nature.\n" + "\n" +
                    "Surrounded by lush greenery and lofty mountains around, this lake is a must visit place to spend a quiet afternoon amidst the hush murmur of the breeze and warm sunlight. Ganga Lake is located 6 kilometres from Itanagar and the calm water body surrounded by primeval vegetation, various flora and huge trees will certainly spellbind you.", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Sela Pass", "The Sela Pass (more appropriately called Se La, as La means Pass) is a high-altitude mountain pass located on the border between the Tawang and West Kameng districts in the Indian state of Arunachal Pradesh. It has an elevation of 4170 m (13,700 ft) and connects the Indian Buddhist town of Tawang to Dirang and Guwahati. The pass carries the National Highway 13 (previously NH 229), connecting Tawang with the rest of India. The pass supports scarce amounts of vegetation and is usually snow-covered to some extent throughout the year. Sela Lake, near the summit of the pass, is one of approximately 101 lakes in the area that are sacred in Tibetan Buddhism. While Sela Pass does get heavy snowfall in winters, it is usually open throughout the year unless landslides or snow require the pass to be shut down temporarily.", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Kamlang Wildlife Sanctuary", "The Kamlang Wildlife Sanctuary, established in 1989, is the 50th Tiger reserve in India. The Sanctuary is rich with floral and faunal diversity. It is situated in the Lohit District of the northeastern Indian state of Arunachal Pradesh. The park is named after the Kamlang River which flows through it. The Mishmi, Digaro Mishmi , and Miju Mishmi people tribal people who reside around the periphery of the sanctuary claim their descent from the King Rukmo of the epic Mahabharata. They believe in a myth of an invisible god known as Suto Phenkhenynon jamalu. An important body of water in the sanctuary is the Glow Lake. Located in tropical and sub-tropical climatic zones, the sanctuary is the habitat of the four big cat species of India: tiger, leopard, clouded leopard and snow leopard.[2][3]", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Tawang monastery", "Tawang Monastery, located in Tawang city of Tawang district in the Indian state of Arunachal Pradesh, is the largest monastery in India. It is situated in the valley of the Tawang Chu, near the small town of the same name in the northwestern part of Arunachal Pradesh, in close proximity to the Chinese and Bhutanese border.\n" + "\n" +
                    "Tawang Monastery is known in Tibetan as Gaden Namgyal Lhatse, which translates to \"the divine paradise of complete victory.\" It was founded by Merak Lama Lodre Gyatso in 1680–1681 in accordance with the wishes of the 5th Dalai Lama, Ngawang Lobsang Gyatso. It belongs to the Gelug school of Vajrayana Buddhism and had a religious association with Drepung Monastery of Lhasa, which continued during the period of British rule.\n" + "\n" +
                    "The monastery is three stories high. It is enclosed by a 925 feet (282 m) long compound wall. Within the complex there are 65 residential buildings. The library of the monastery has valuable old scriptures, mainly Kangyur and Tengyur.", "17.741037,83.315813"));
            famousPlacesModelList.add(new FamousPlacesModel("Mehao Wildlife Sanctuary", "The Mehao wildlife sanctuary was declared with an aim to conserve the biodiversity around the Mehao Lake.[1] The sanctuary is gifted with virgin natural lush green forest and lakes. The sancturary harbours some rare varieties of orchids. The altitude of the sanctuary varies from 900 to 3500 meters. The sanctuary covers 281.5 km2 (108.7 sq mi). Its average winter temperature is 12 °C (54 °F) and its average summer temperature is 36 °C (97 °F).", ""));


        } else if (state_name.equals("Assam")) {
            famousPlacesModelList.add(new FamousPlacesModel("Kaziranga National Park", "Kaziranga National Park is a national park in the Golaghat and Nagaon districts of the state of Assam, India. The park, which hosts two-thirds of the world's great one-horned rhinoceroses, is a World Heritage Site.[2] According to the census held in March 2018 which was jointly conducted by the Forest Department of the Government of Assam and some recognized wildlife NGOs, the rhino population in Kaziranga National Park is 2,613. It comprises 1,641 adult rhinos (642 males, 793 females, 206 unsexed); 387 sub-adults (116 males, 149 females, 122 unsexed); and 385 calves.[3]", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Brahmaputra River", "The Brahmaputra (/ˌbrɑːməˈpuːtrə/),[3] also known as the Yarlung Tsangpo in Tibet, the Siang/Dihang River in Arunachal Pradesh, Luit in Assamese, and Jamuna River in Bangladesh, is a trans-boundary river which flows through Tibet, India, and Bangladesh. It is the 9th largest river in the world by discharge, and the 15th longest.", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Kamakhya Temple", "The Kamakhya Temple at Nilachal hills in Guwahati, Assam is one of the oldest and most revered centres of Tantric practices.[3] The temple is the center of the Kulachara Tantra Marga and the site of the Ambubachi Mela, an annual festival that celebrates the menstruation of the goddess.[4] Structurally, the temple is dated to the 8th-9th century with many subsequent rebuildings[5]—and the final hybrid architecture defines a local style called Nilachal.[6] It is also one of the oldest of the 51 pithas in the Shakta tradition.[7] An obscure place of worship for much of history it became an important pilgrimage destination, especially for those from Bengal, in the 19th century during colonial rule.[8]", ""));
            famousPlacesModelList.add(new FamousPlacesModel("UmaNanda temple", "Umananda Devaloi (Pron: ˈʊməˌnændə ˈdeɪvəˌlɔɪ) is a Shiva temple located at the Umananda Island (Peacock Island) in the middle of river\n" + "\n" +
                    "Brahmaputra just opposite the office of the Deputy Commissioner of Kamrup or the Kachari Ghat in Guwahati.\n" + "\n" +
                    "It is known as smallest inhabited riverine island in the world. Country boats that are available on the bank of Brahmaputra take the visitors to the island. The mountain on which the temple has been built is known as Bhasmacala.It was built in 1694CE in the order of King Gadadhar Singha but was broken down by an earthquake in 1867.", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Pobitora Life Sanctuary", "Pobitora Wildlife Sanctuary (IPA: [ˈpəʊbɪˌtɔ:rə]) is a wildlife sanctuary on the southern bank of the Brahmaputra in Morigaon district in Assam, India. It was declared in 1987 and covers 38.85 km2 (15.00 sq mi), providing grassland and wetland habitat for the Indian rhinoceros. Pobitora Wildlife Sanctuary holds one of the largest Indian rhinoceros populations in Assam.[1][2]", ""));


        } else if (state_name.equals("Bihar")) {
            famousPlacesModelList.add(new FamousPlacesModel("Patna Museum", "Patna Museum is the state museum of the Indian state of Bihar. Started on 3 April 1917 during the British Raj to house the historical artefacts found in the vicinity of Patna,[3][4][5] it is in the style of Mughal and Rajput architecture and is known locally as the Jadu Ghar. The artefacts from ancient India era to 1764 have now been transferred to Bihar Museum.\n" +
                    "\n" +
                    "The KP Jayaswal Research Institute (KPJRI) which carries out research in the field of history and archaeology also operates out of Patna Museum and was established by the Bihar Government.[6]", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Bodh Gaya", "Bodh Gaya is a religious site and place of pilgrimage associated with the Mahabodhi Temple Complex in Gaya district in the Indian state of Bihar. It is famous as it is the place where Gautama Buddha is said to have attained Enlightenment (Pali: bodhi) under what became known as the Bodhi Tree.[2] Since antiquity, Bodh Gaya has remained the object of pilgrimage and veneration both for Hindus and Buddhists.[3] In particular, archaeological finds including sculptures show that the site was in use by Buddhists since the Mauryan period.[4]", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Nalanda", "Nalanda (Nālandā, pronounced [naːlən̪d̪aː]) was a renowned mahavihara (Buddhist monastic university) in ancient Magadha (modern-day Bihar), India.[5][6] Considered by historians to be the world's first residential university[7] and among the greatest centers of learning in the ancient world, it was located near the city of Rajagriha (now Rajgir) and about 90 kilometres (56 mi) southeast of Pataliputra (now Patna). Operating from 427 until 1197 CE,[8][9] Nalanda played a vital role in promoting the patronage of arts and academics during the 5th and 6th century CE, a period that has since been described as the \"Golden Age of India\" by scholars.[10]", ""));
            famousPlacesModelList.add(new FamousPlacesModel("The Archaeological site of Vaishali", "Vaishali, Vesali or Vaiśālī was a city in present-day Bihar, India, and is now an archaeological site. It is a part of the Tirhut Division.[1]\n" + "\n" +
                    "It was the capital city of the Vajjika League of Vrijji mahajanapada, considered one of the first examples of a republic around the 6th century BCE. Gautama Buddha preached his last sermon before his death in c. 483 BCE, then in 383 BCE the Second Buddhist council was convened here by King Kalasoka, making it an important place in both Jain and Buddhist religions.[2][3][4] It contains one of the best-preserved of the Pillars of Ashoka, topped by a single Asiatic lion.\n" + "\n" +
                    "Vaishali is also home to possibly the earliest known example of a stupa, the Buddha relic stupa which is said to contain the ashes of the Buddha.[5][6]", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Madhubani", "Madhubani is a City Municipal Corporation and headquarter of Madhubani district. Madhubani is situated in the Indian state of Bihar. It comes under Darbhanga Division. It is situated at 26 km northeast of Darbhanga City.The Madhuban Raj in Madhubani was created as a consequence.[2] The word \"Madhuban\" means \"forest of honey\" from which Madhubani is derived, but sometimes it is also known as \"madhu\"+\"vaani\" meaning \"sweet\" \"voice/language\".[3]", ""));

        } else if (state_name.equals("Chhattisgarh")) {
            famousPlacesModelList.add(new FamousPlacesModel("Chitrakote waterfalls", "The Chitrakote Falls[5] is located on the Indravati River. The river originates in the Kalahandi district of Odisha, in the Vindhya Range of hills, flows westward, and then forms a fall at Chitrakote, after which it finally flows into the Godavari River at Bhadrakali,[6] after traversing 240 miles (390 km) in the state.[7][8] The free drop of the falls is a sheer height of about 30 metres (98 ft). Because of its horseshoe shape, it is often compared with the world-famous Niagara Falls in the United States, and is given the sobriquet \"the Small Niagara Falls\". During the rainy season, from July to October, rainbows are created with sun rays reflecting on mist from the waterfall.[9]\n" +
                    "\n" + "A small Hindu shrine dedicated to the god Shiva and several naturally created grottoes named \"Parvati caves\" (named after Shiva's wife Parvati) are located on the left bank of the Chitrakote Falls. The river flows sluggishly on the upstream side of the falls due to its meandering nature as it drains through the plains of Jagdalpur. This reach of the river valley has very little forest cover. Below the falls the river traverses the Bodhghat forested area and the river regime undergoes a drastic change in its flow conditions. Aeration processes and the forest in the downstream area filter the silt in the river.[10] The weather in the area is generally pleasant except in the summer season when it is hot due to the absence of shade from vegetation in the area.[11]", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Tamor Pingla", "Tamor Pingla Wildlife Sanctuary is located in Chhattisgarh in Surajpur District and derives its name from the most prominent features of the area - Tamor Hill and PinglaNalla. Considered as one of the virgin natural reserves and instances of the rich wildlife that the state has to offer, this sanctuary is raw and untouched, and completely away from commercial activities.\n", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Bhairamgarh", "Bhairamgarh is a Town and Tehsil in Bijapur District of Chhattisgarh. According to census 2011 information the sub-district code of Bhairamgarh Block (CD) is 03379. Total area of bhairamgarh tehsil is 2,698 km² including 2,662.31 km² rural area and 35.96 km² urban area. Bhairamgarh tehsil has a population of 83,706 peoples, out of which urban population is 9,026 while rural population is 74,680. Bhairamgarh has a population density of 31.02 inhabitants per square kilometre. There are about 17,206 houses in the sub-district, including 2,006 urban houses and 15,200 rural houses.\n" +
                    "\n" + "When it comes to literacy, 26.28% population of bhairamgarh tehsil is literate, out of which 33.98% males and 18.58% females are literate. There are about 273 villages in bhairamgarh tehsil, which you can browse from bhairamgarh tehsil villages list (along with gram panchayat information) below.", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Sita Nadi wildlife sanctuaries ", "Sitanadi Wildlife Sanctuary is located in Dhamtari District, Chhattisgarh, India.[1] Sitanadi Wildlife Sanctuary is a famous tourist attraction which is frequented by wildlife enthusiasts throughout the year. The wildlife sanctuary was established in 1974 under Wildlife Protection Act of 1972. This sanctuary sprawls over an area of 556 km2 and has an altitude ranging between 327 and 736 m above the sea level. It is named after Sitanadi River which originates from this sanctuary and joins Mahanadi River near Deokhut. Sitanadi Wildlife Sanctuary is known for its lush green flora and rich and unique and diverse fauna and has great potential to emerge as one of the finest wildlife destinations in central India.\n" +
                    "\n" +
                    "\n" +
                    "A deep forest at Sitanadi Wildlife Sanctuary of Chattisgharh\n" +
                    "Teak and bamboo predominate among the vegetation. Animals include Tigers, Leopards, Flying Squirrels, Jackals, Four-horned Antelopes, Chinkara, Black Buck, Jungle Cat, Barking Deer, Porcupine, Monkey, Bison, Striped Hyena, Sloth Bear, Wild Dogs, Chital, Sambar, Nilgai , Gaur, Muntjac, Wild Boar, Cobra, Python among many others.[2] The sanctuary is also a paradise for bird watchers, as over 175 species of birds can be seen here.[3]", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Indravati national park", "Indravati National Park is a national park located in Bijapur district of Chhattisgarh state in India.[1] The park derives its name from the Indravati River, which flows from east to west and forms the northern boundary of the reserve with the Indian state of Maharashtra.\n" +
                    "\n" + "Indravati National Park is among the finest and most famous wildlife parks of Chhattisgarh. It is one of three Project Tiger sites in Chhattisgarh, along with Udanti-sitanadi, and is home to one of the last remaining populations of the endangered wild water buffalo. With a total area of approximately 2799.08 km2, Indravati attained the status of a national park in 1981 and a tiger reserve in 1983, becoming one of the most famous tiger reserves in India.", ""));
        } else if (state_name.equals("Goa")) {
            famousPlacesModelList.add(new FamousPlacesModel("Calangute beach", "Calangute is a town in the North Goa district of the Indian state of Goa. It is famous for its beach, the largest in North Goa and a popular tourist destination. The peak tourist season is during Christmas and New Year, and during the summer in May. During the monsoon season, from June through September, the sea can be rough and swimming is prohibited. The beach offers water sport activities like parasailing and water skiing, among others.", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Palolem beach", "Palolem Beach is situated in Canacona in southern Goa, India. The beach attracts many international tourists, mainly during the winter season between November and March. It is considered to be one of the region's most beautiful beaches.Palolem Beach is largely unspoiled and is inhabited by both local fishermen and by foreign tourists who live in shacks along the shore or in the main village itself.[1] It is about one mile (approximately 1.61 km) long and is crescent-shaped; one can view the entire beach from either end. Both ends of the beach consist of rocks jutting out into the sea. The depth of the sea increases gradually, being shallowest at the northern end of the beach, making it safe for average swimmers, and the currents are not fast.", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Basilica of Bom Jesus", "The Basilica of Bom Jesus (Portuguese: Basílica do Bom Jesus; Konkani: Borea Jezuchi Bajilika) is a Catholic basilica located in the Goa situated in the Konkan region of India. It is both a pilgrimage centre and also the most iconic monument of all the churches and convents of Goa, recognised by UNESCO as a World Heritage Site.[1][2] The basilica is located in Old Goa, former capital of Portuguese India, and holds the mortal remains of St Francis Xavier.[3]\n" +
                    "\n" +
                    "Bom Jesus (meaning, \"Good/ Infant Jesus\" in Portuguese) is the name used for the Ecce Homo in countries of the Lusosphere. This Jesuit church is India's first minor basilica, and is considered to be one of the best examples of baroque architecture and Portuguese Colonial architecture in India. It is one of the Seven Wonders of Portuguese Origin in the World.\n" +
                    "\n" +
                    "Pope Pius XII raised this sanctuary to the status of basilica via the Pontifical decree “Priscam Goae” on 20 March 1946. Signed and notarized by Cardinal Giovanni Battista Montini.", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Dudhsagar Waterfalls", "Dudhsagar Falls (lit. 'Sea of Milk') is a four-tiered waterfall located on the Mandovi River in the Indian state of Goa. It is 60 km from Panaji by road and is located on the Belgavi–Vasco Da Gama rail route about 46 km east of Madgaon and 80 km south of Belgavi. Dudhsagar Falls is amongst India's tallest waterfalls with a height of 310 m (1017 feet) and an average width of 30 metres (100 feet).\n" +
                    "\n" +
                    "The falls is located in the Bhagwan Mahaveer Sanctuary and Mollem National Park among the Western Ghats. The falls is a punctuation mark in the journey of the Mandovi River from the Western Ghats to Panjim where it meets the Arabian sea. The area is surrounded by deciduous forests with rich biodiversity. This waterfall is also known as Tambdi Surla to some of the local people. The falls are not particularly spectacular during the dry season but during the monsoon season, however, the falls are fed by rains and form a huge force of water.", ""));
        } else if (state_name.equals("Gujarat")) {
            famousPlacesModelList.add(new FamousPlacesModel("Gir National Park", "Gir National Park is the only place in the world outside Africa where a lion can be seen in its natural habitat. The lions of Gir are a majestic animal, averaging 2.75 metres in length, and with a bigger tail tassle, bushier elbow tufs and prominent belly folds than his African cousin which has larger mane. Gir is a home to 40 species of mammals and 425 species of birds.\n" +
                    "\n" +
                    "We all know, Gir is the only natural habitat of world popular Asiatic Lions. Where our tailor made Gir Wild Life Tour Package gives you an unparalleled opportunity to watch those rare Asiatic Lions coupled with thousands of other elusive wild animals and hard-to-find birds like uncommon Asiatic wild ass, hyenas, Gir foxes, pygmy woodpecker, brown fish owl and black buck etc, it will make sure that you receive the highest standards of luxury, comfort and travel. Additionally, all this is available at very competitive rates.", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Bhuj", "Bhuj was founded by Rao Hamir in 1510 and was made the capital of Kutch by Rao Khengarji I in 1549.[3] Its foundation stone as state capital was formally laid on Vikram Samvat 1604 Maagha 5th (approx. 25 January 1548). From 1590 onwards, when Rao was forced to acknowledge the Mughal supremacy, Bhuj came to be known as Suleiman Nagar amongst Muslims. The city's walls were built by Rao Godji I in 1723[dubious – discuss], and the Bhujia Fort by Devkaran Seth in Rao Deshalji I's time (1718 - 1741).[4]\n" +
                    "\n" +
                    "Bhuj has been attacked six times. In two instances, the defense was successful and in four other instances, the defense failed. In 1728, an attack by Sarbuland Khan, Mughal Viceroy of Gujarat, was repulsed by Rao Deshalji I, and, in 1765 Mian Ghulam Shah Kalhoro was, by a timely display of the strength of the fortifications, induced to withdraw. During the civil troubles of the reign of the Rao Rayadhan III, Bhuj was thrice taken, by Meghji Seth in 1786, by Hansraj in 1801, and by Fateh Muhammad in 1808. On 26 March 1819, the hill fort of Bhujia was captured by a British detachment under Sir William Keir.[4]\n" +
                    "\n" + "In 1818, Bhuj had a population of 20,000 people. The earthquake on 16 June 1819 destroyed nearly 7000 houses with a loss of an estimated 1140 human lives. About one-third of the buildings that escaped ruin were heavily damaged, and the north face of the town wall was leveled with the ground.", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Sabarmati Ashram", "Sabarmati Ashram (also known as Gandhi Ashram) is located in the Sabarmati suburb of Ahmedabad, Gujarat, adjoining the Ashram Road, on the banks of the River Sabarmati, 4 miles (6.4 km) from the town hall. This was one of the many residences of Mahatma Gandhi who lived at Sabarmati (Gujarat) and Sevagram (Wardha, Maharashtra) when he was not travelling across India or in prison.[1] He lived in Sabarmati or Wardha for a total of twelve years with his wife Kasturba Gandhi and followers, including Vinoba Bhave. The Bhagavad Gita was recited here daily as part of the Ashram schedule.\n" +
                    "\n" + "It was from here that Gandhi led the Dandi march also known as the Salt Satyagraha on 12 March 1930. In recognition of the significant influence that this march had on the Indian independence movement, the Indian government has established the ashram as a national monument.", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Statue of Unity", "The Statue of Unity is the world's tallest statue, with a height of 182 metres (597 feet),[3] located near Kevadia in the state of Gujarat, India. It depicts Indian statesman and independence activist Vallabhbhai Patel (1875–1950), who was the first deputy prime minister and home minister of independent India and an adherent of Mahatma Gandhi. Patel was highly respected for his leadership in uniting 562 princely states of India to form the single Union of India. The statue is located in Gujarat on the Narmada River in the Kevadiya colony, facing the Sardar Sarovar Dam 100 kilometres (62 mi) southeast of the city of Vadodara.[4]\n" +
                    "\n" + "The project was first announced in 2010, and construction started in October 2013 by Indian company Larsen & Toubro, with a total construction cost of ₹27 billion (US$422 million).[5] It was designed by Indian sculptor Ram V. Sutar and was inaugurated by the Prime Minister of India, Narendra Modi, on 31 October 2018, the 143rd anniversary of Patel's birth.[6]", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Great Rann of Katch", "The Little Rann of Kutch, including the Banni grasslands on its southern edge, is situated in the district of Kutch and comprises some 30,000 square kilometres (10,000 sq mi) between the Gulf of Kutch and the mouth of the Indus River in southern Pakistan. The marsh can be accessed from the village of Kharaghoda in Surendranagar District.[4] The Great Rann of Kutch together with the Little Rann of Kutch is called Rann of Kutch.\n" +
                    "\n" + "In India's summer monsoon, the flat semi-desert of salty clay and mudflats, which average 15 meters above sea level, fills with standing water. In very wet years, the wetland extends from the Gulf of Kutch on the west through to the Gulf of Khambhat on the east.[5][6]\n" +
                    "\n" + "The area was a vast shallow of the Arabian Sea until continuing geological uplift closed off the connection with the sea, creating a vast lake that was still navigable during the time of Alexander the Great. The Ghaggar River, which presently empties into the semi-desert of northern Rajasthan, formerly emptied into the Rann of Kutch, but the lower reaches of the river dried up as its upstream tributaries were captured by the Indus and Ganges thousands of years ago. Traces of the delta and its distributary channels on the northern boundary of the Rann of Kutch were documented by the Geological Survey of India in 2000.", ""));
        } else if (state_name.equals("Haryana")) {
            famousPlacesModelList.add(new FamousPlacesModel("Kingdom of Dreams", "The complex was inaugurated on 29 January 2010, by Chief Minister of Haryana Bhupinder Singh Hooda, with appearances by Javed Akhtar, Ehsaan Noorani, and Loy Mendonsa. It is a project of The Great Indian Nautanki Company, a joint venture between events firm Wizcraft International Entertainment and real estate developer Apra Group.[1] The companies described Kingdom of Dreams as being a complex \"where ethnic Indian culture meets modern entertainment\", and compared it to New York City's Broadway.[2]\n" +
                    "\n" +
                    "The Culture Gully portion of the complex opened on 30 July 2010.[2] On 28 August 2010, the official song of the 2010 Commonwealth Games, \"Jiyo Utho Bado Jeeto\", was presented during a promotional event at the complex.[3][4] Kingdom of Dreams officially opened to the public on 18 September 2010.[5] On 19 September 2010, actor Shah Rukh Khan was announced at the complex's \"global ambassador\".[6]\n" +
                    "\n" +
                    "After its successful opening, GINC disclosed plans to potentially open a second, larger Kingdom of Dreams complex in Mumbai, and similar complexes internationally in China, Dubai, Singapore, South Africa, as well as the United States (with a particular focus on Las Vegas and a potential partnership with real estate developer Steve Wynn).[7][8]", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Brahma Sarovar", "According to stories of itihasa , Lord Brahma created the universe from the land of Kurukshetra after a huge yajna with the help of Hitesh. The Brahma Sarovar here is believed to be the cradle of civilization. The sarovar is also mentioned in the eleventh century AD memoirs of Al Beruni, called 'Kitab-ul-Hind'. The sarovar also has a mention in Mahabharata citing its use by Duryodhana to hide himself underwater on the concluding day of the war. At that time is was believed Hitesh was the guard of Bhrama Sarover. It is believed that he is still alive and living near Bhrama Sarover.\n" +
                    "\n" +
                    "A sacred shrine dedicated to Lord Shiva stands within the sarovar, accessible by a small bridge. According to scriptures, bathing in this sarovar increases the sanctity of performing the 'ashvamedh yajna'. The pool offers a breath-taking sight during the Gita Jayanti celebrations held each year in the last week of November and early December when a 'deep daan' ceremony of floating lamps in water and [Aarti] occurs.[2] This also happens to be the time when migratory birds from distant places arrive at the sarovar. The Birla Gita Mandir and Baba Nath's haveli and temple are the neighbouring attractions.", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Kurukshetra", "According to the Puranas, Kurukshetra is a region named after King Kuru, the ancestor of Kauravas and Pandavas in the Kuru kingdom, as depicted in epic Mahabharata. The Kurukshetra War of the Mahabharata is believed to have taken place here. Thaneswar whose urban area is merged with Kurukshetra is a pilgrimage site with many locations attributed to Mahabharata.[3]\n" +
                    "\n" + "In the Vedas Kurukshetra is described not as a city but as a region (\"kshetra\" means \"region\" in Sanskrit). The boundaries of Kurukshetra correspond roughly to the central and western parts of the state of Haryana and southern Punjab. According to the Taittiriya Aranyaka 5.1.1., the Kurukshetra region is south of Turghna (Srughna/Sugh in Sirhind, Punjab), north of Khandava (Delhi and Mewat region), east of Maru (desert), and west of Parin.[4]", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Morni Hills", "Morni is a village and tourist attraction in the Morni Hills at the height of 1,267 metres (4,157 ft) in the Panchkula district of the Indian state of Haryana. It is located around 45 kilometres (28 mi) from Chandigarh, 35 kilometres (22 mi) from Panchkula city and is known for its Himalayan views, flora, and lakes. The name of Morni is believed to derive from a queen who once ruled the area two thousand years back. She was a just and noble ruler of her Queendom and after her the Morni was jagir of the Raja of Morni, kotaha and Pindrawal Raja Mir Syed Muhammad Baquar Ali Khan CIE.", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Zakir Hussain Rose Garden", "Zakir Hussain Rose Garden, is a botanical garden in Chandigarh, India and spread over 30 acres (120,000 m2) of land,[1] with 50,000 rose-bushes of 1600 different species.[2] Named after India's former president, Zakir Hussain and created in 1967 under the guidance of Mohinder Singh Randhawa, Chandigarh's first chief commissioner, the garden has the distinction of being Asia's largest.[2] The garden has not only roses, but also trees of medicinal value. Some of the medicinal plants that can be spotted here are bel, bahera, harar, camphor and yellow gulmohar. The rose plants have been planted in carved-out lawns and flower beds.\n" +
                    "\n" + "Apart from serving as a host of other events, the Zakir Rose Garden serves as the venue for hosting an annual rose festival called Rose Festival, a major cultural event in Chandigarh during February or March. Celebrated mainly as a tribute to the magnificence of the rose itself, the attractions include food, drinks, joyrides, and contests of varying nature, such as photography, gardening, landscaping, bonsai, and Rose Prince and Princess. The contests are open to the residents or institutions from nearby places.[3][4]", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Sultanpur Bird Sanctuary", "Sultanpur Bird Sanctuary is a very popular national park of India. Located in Sultanpur village, Farukhnagar, Gurugram district in Haryana state. Sultanpur village is located 40 km from Dhaula Kuan in Delhi and 15 km from Gurugram city on the Gurugram – Jhajjar highway. This bird sanctuary, ideal for birding and bird lookers, is best visited in winters when many migratory birds come here.\n" +
                    "\n" +
                    "Haryana government has carried out a number of development works at Sultanpur Bird Sanctuary like construction of mounds, widening of paths, and digging four tube wells. Efforts are being made to improve vegetation in the area by planting more trees, which are popular with the birds like ficus spp. Acacia Nilotica, Acacia Tortilis, Beris and Neem.\n" +
                    "\n" +
                    "Among approximately 1,800 migratory bird species out of total approximately 9,000-10,000 species of birds in the world, nearly three thousand species migrate to India due to seasonal changes, including 175 long-distance migration species that use the Central Asian Flyway route which also include Amur falcons, Egyptian vultures, plovers, ducks, storks, ibises, flamingos, jacanas, pochards and sociable lapwing.[2][3] Among these approximately 250 species of Birds are found at Sultanpur Bird Sanctuary. Some of them are resident, while others come from distant regions like Siberia, Europe and Afghanistan.", ""));
        } else if (state_name.equals("Himachal Pradesh")) {
            famousPlacesModelList.add(new FamousPlacesModel("Shimla", "Shimla (English: /ˈʃɪmlə/; Hindi: [ˈʃɪmla] (listen); also known as Simla, the official name until 1972)[10] is the capital and the largest city of the northern Indian state of Himachal Pradesh. In 1864, Shimla was declared as the summer capital of British India. After independence, the city became the capital of East Punjab and was later made the capital city of Himachal Pradesh. It is the principal commercial, cultural and educational centre of the state.\n" +
                    "\n" +
                    "Small hamlets were recorded before 1815 when British forces took control of the area. The climatic conditions attracted the British to establish the city in the dense forests of the Himalayas. As the summer capital, Shimla hosted many important political meetings including the Simla Accord of 1914 and the Simla Conference of 1945. After independence, the state of Himachal Pradesh came into being in 1948 as a result of the integration of 28 princely states. Even after independence, the city remained an important political centre, hosting the Simla Agreement of 1972. After the reorganisation of the state of Himachal Pradesh, the existing Mahasu district was named Shimla.", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Manali", "Manali is a town, near Kullu town in Kullu district in the Indian state of Himachal Pradesh.[2] It is situated in the northern end of the Kullu Valley, formed by the Beas River. The town is located in the Kullu district, approximately 270 kilometres (170 mi) north of the state capital of Shimla and 544 kilometres (338 mi) northeast of the national capital of New Delhi. With a population of 8,096 people recorded in the 2011 Indian census Manali is the beginning of an ancient trade route through Lahaul (H.P) and Ladakh, over the Karakoram Pass and onto Yarkand and Hotan in the Tarim Basin of China. Manali is a popular tourist destination in India and serves as the gateway to the Lahaul and Spiti district as well as the city of Leh in Ladakh.[3]", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Dalhousie", "If you are looking for a serene and calm location to harmonize your soul, then Dalhousie would be an ideal place. The galore of luscious meadows with a mesmerizing blend of fir and pine trees would enlighten your body and mind for a memorable experience. This stunning hill station is ideal for family vacations and romantic honeymoons, and even foreign tourists prefer to visit this impeccable location.\n" +
                    "\n" +
                    "There are many eminent places in Dalhousie, which should be a must-visit on your list. You would certainly feel like in fairyland by witnessing nature’s imperious form in many parts of this stunning hill station. Khajjiar is a popular spot in Dalhousie, and its astonishing beauty gives it the title of “ Switzerland of India.” This glorious place would certainly take your breath away with its lush greenery and alluring atmosphere. Along with the spell bounding meadows, Khajjiar is also renowned for its divine temples.\n" +
                    "\n" +
                    "For all the adventurous freaks, activities like Paragliding, Zorbing, and trekking are regularly organized in different locations of Dalhousie. You should also witness the astonishing site of Satdhara Falls for a rejuvenating experience. With incredible therapeutic properties, the waterfalls are quite efficient against several ailments. This place is also ideal for trekking, with a soul-stirring experience of witnessing nature’s imperious form.", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Rohtang La", "The pass is open from May to November. It is not particularly high or difficult to cross on foot by Himalayan standards, but it has a well-deserved reputation for being dangerous because of unpredictable snowstorms and blizzards.[7]\n" +
                    "\n" +
                    "This pass is an ancient trade route between the people on either side of Pir Panjal. The local name for this pass is a generic name of pass.[citation needed] There are many other passes in Lahaul and Spiti which have specific names (Kunzam La, Baralacha La, etc.). This is suggestive of the fact that this must have been the oldest and most frequented pass in the region, or the fact that it is the main pass leading from one cultural region to another, quite different one, to the north. The name Rohtang comes from Persian/ Farsi words Ruh+ Tang which means pile of dead bodies.[citation needed]\n" +
                    "\n" +
                    "The former National Highway 21 (NH 21, now numbered NH 3), the road through the Kullu Valley, terminates at Manali. The road northwards over the Rohtang Pass to Keylong in Lahaul and Spiti district and on to Leh in Ladakh is not a national highway. Nonetheless, the Leh-Manali Highway has become very busy during the summer months as an alternate military route since the Kargil Conflict in 1999. Traffic jams are common as military vehicles, trucks, and goods carriers try to navigate the tight roads and rough terrain, compounded by snow and ice at certain points and the large number of tourist vehicles.", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Spiti Valley", "Spiti (pronounced as Piti in Bhoti language) is a high-altitude region of the Himalayas, located in the north-eastern part of the northern Indian state of Himachal Pradesh. The name \"Spiti\" means \"The middle land\", i.e. the land between Tibet and India.[2] Spiti incorporates mainly the valley of the Spiti River, and the valleys of several rivers that feed into the Spiti River. Some of the prominent side-valleys in Spiti are the Pin valley and the Lingti valley. Spiti is bordered on the east by Tibet, on the north by Ladakh, on the west and southwest by Lahaul, on the south by Kullu, and on the southeast by Kinnaur. The valley and its surrounding regions are among the least populated regions of India. Spiti has a cold desert environment. The Bhoti-speaking local population follows Tibetan Buddhism.", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Kasauli ", "Kasauli is a Cantonment Board city in district of Solan, Himachal Pradesh. The Kasauli city is divided into 6 wards for which elections are held every 5 years. The Kasauli Cantonment Board has population of 3,885 of which 2,183 are males while 1,702 are females as per report released by Census India 2011.\n" +
                    "\n" +
                    "Population of Children with age of 0-6 is 406 which is 10.45% of total population of Kasauli (CB). In Kasauli Cantonment Board, Female Sex Ratio is of 780 against state average of 972. Moreover, Child Sex Ratio in Kasauli is around 888 compared to Himachal Pradesh state average of 909. Literacy rate of Kasauli city is 91.23% higher than state average of 82.80%. In Kasauli, Male literacy is around 94.05% while female literacy rate is 87.56%.[citation needed]", ""));
        } else if (state_name.equals("Jammu and Kashmir")) {
            famousPlacesModelList.add(new FamousPlacesModel("Alchi Monastery", "Alchi Monastery or Alchi Gompa (also Alci) is a Tibetan Buddhist monastery, known more as a monastic complex (chos-'khor) of temples in Alchi village in the Leh District, under the Ladakh Autonomous Hill Development Council of the Ladakh Union Territory. The complex comprises four separate settlements in the Alchi village in the lower Ladakh region with monuments dated to different periods. Of these four hamlets, Alchi monastery is said to be the oldest and most famous. It is administered by the Likir Monastery.[1][2][3]\n" +
                    "\n" +
                    "Alchi is also part of the three villages (all in lower Ladakh region) which constitute the ‘Alchi group of monuments’; the other two villages adjoining Alchi are the Mangyu and Sumda Chun. The monuments in these three villages are stated to be of \"unique style and workmanship’, but the Alchi monastic complex is the best known.[1][2]\n" +
                    "\n" +
                    "The monastery complex was built, according to local tradition, by the great translator Guru Rinchen Zangpo between 958 and 1055. However, inscriptions in the preserved monuments ascribe it to a Tibetan noble called Kal-dan Shes-rab later in the 11th century.[2][4] Dukhang or Assembly Hall and the Main Temple (gTsug-lag-khang), which is a three-storied temple called the Sumtseg (gSum-brtsegs), are built in the Kashmiri style as seen in many monasteries; the third temple is called the Manjushri Temple ('Jam-dpal lHa-khang). Chortens are also an important part of the complex.[1][2]", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Kashmir", "Kashmir (IPA: [kaʃmiːr]) is the northernmost geographical region of the Indian subcontinent. Until the mid-19th century, the term \"Kashmir\" denoted only the Kashmir Valley between the Great Himalayas and the Pir Panjal Range. Today, the term encompasses a larger area that includes the Indian-administered territories of Jammu and Kashmir and Ladakh, the Pakistani-administered territories of Azad Kashmir and Gilgit-Baltistan, and the Chinese-administered territories of Aksai Chin and the Trans-Karakoram Tract.[1][2][3]\n" +
                    "\n" +
                    "In 1820 the Sikh Empire, under Ranjit Singh, annexed Kashmir.[4] In 1846, after the Sikh defeat in the First Anglo-Sikh War, and upon the purchase of the region from the British under the Treaty of Amritsar, the Raja of Jammu, Gulab Singh, became the new ruler of Kashmir. The rule of his descendants, under the paramountcy (or tutelage[5][6]) of the British Crown, lasted until the Partition of India in 1947, when the former princely state of the British Indian Empire became a disputed territory, now administered by three countries: India, Pakistan, and China.", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Spituk Monastery", "Spituk Monastery, also known as Spituk Gompa or Pethup Gompa, is a Buddhist monastery in Spituk, Leh district, Ladakh, northern India. 8 kilometres from Leh.[1] The site of Spituk was blessed by the Arhat Nyimagung. It was founded by Od-de, the elder brother of Lha Lama Changchub Od when he came to Maryul in the 11th Century. He introduced the monastic community. When Lotsewa Rinchen Zangpo (Translator) came to that place he said that an exemplary religious community would arise there and so the monastery was called spituk (exemplary). During the time of Dharma raja Gragspa Bum-Ide the monastery was restored by Lama Lhawang Lodos and the stainless order of Tsonkhapa was introduced and it has remained intact as such till present. Founded as a Red Hat institution, the monastery was taken over by the Gelugpa (Yellow Hat sect) in the 15th century.\n" +
                    "\n" +
                    "The monastery contains 100 monks and a giant statue of Kali (unveiled during the annual festival).\n" +
                    "\n" +
                    "Every year the Gustor Festival is held at Spituk from the 27th to 29th day in the eleventh month of the Tibetan calendar.", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Pangong Tso", "Pangong Tso or Pangong Lake (Tibetan: སྤང་གོང་མཚོ;[3] Chinese: 班公错; pinyin: Bān gōng cuò; Hindi: पैंगोंग झील) is an endorheic lake spanning eastern Ladakh and West Tibet situated at an elevation of 4,225 m (13,862 ft). It is 134 km (83 mi) long and divided into five sublakes, called Pangong Tso, Tso Nyak, Rum Tso (twin lakes) and Nyak Tso. Approximately 50% of the length of the overall lake lies within Tibet in China, 40% in Ladakh, India and the remaining 10% is disputed and is a de-facto buffer zone between India and China. The lake is 5 km (3.1 mi) wide at its broadest point. All together it covers almost 700 km2. During winter the lake freezes completely, despite being saline water. It has a land-locked basin separated from the Indus River basin by a small elevated ridge, but is believed to have been part of the latter in prehistoric times.", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Jammu", "Jammu /ˈdʒʌmuː/ is the winter capital of the Indian union territory of Jammu and Kashmir. It is the headquarters and the largest city in Jammu district of the union territory. Lying on the banks of the river Tawi, the city of Jammu, with an area of 240 km2 (93 sq mi),[3] is surrounded by the Himalayas in the north and the northern-plains in the south. Jammu is the second most populous city of the union territory. Three battles have been fought in the city: first by the founder Raja Mal Dev against Timur in Battle of Jammu (1399), second by Sardar Bhag Singh against Mughal army in Battle of Jammu (1712)[11] and the third by Mian Dido & Maharaja Gulab Singh against Ranjit Singh's army in Battle of Jammu (1808).[12]\n" +
                    "\n" +
                    "Known as the City of Temples for its ancient temples and Hindu shrines, Jammu is the most visited place in the union territory. Jammu city shares its borders with the neighbouring Samba district.", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Zanskar", "Zanskar, Zahar (locally) or Zangskar, is a tehsil of Kargil district, in the Indian union territory of Ladakh. The administrative centre is Padum (former Capital of Zanskar). Zanskar, together with the neighboring region of Ladakh, was briefly a part of the kingdom of Guge in Western Tibet. Zanskar lies 250 km south of Kargil town on NH301.\n" +
                    "\n" +
                    "The Zanskar Range is a mountain range in the union territory of Ladakh that separates the Zanskar valley from Indus valley at Leh. Geologically, the Zanskar Range is part of the Tethys Himalaya, an approximately 100-km-wide synclinorium formed by strongly folded and imbricated, weakly metamorphosed sedimentary series. The average height of the Zanskar Range is about 6,000 m (19,700 ft). Its eastern part is known as Rupshu. The Zanskar had a population of approximately 20,000 in 2020.[1] There has been demands to convert Zanskar into a district.[2][3]", ""));
        } else if (state_name.equals("Jharkhand")) {
            famousPlacesModelList.add(new FamousPlacesModel("Ranchi Hills", "Ranchi (/ˈrɑːntʃi/ (listen), Hindi: [ˈrãːtʃiː]) is the capital of the Indian state of Jharkhand.[6] Ranchi was the centre of the Jharkhand movement,[7] which called for a separate state for the tribal regions of South Bihar, northern Odisha, western West Bengal and the eastern area of what is present-day Chhattisgarh. The Jharkhand state was formed on 15 November 2000 by carving out the Bihar divisions of Chota Nagpur and Santhal Parganas. Ranchi has been selected as one of the hundred Indian cities to be developed as a smart city under PM Narendra Modi's flagship Smart Cities Mission.[8]\n" +
                    "\n" +
                    "During the time of the British Raj, the city was the summer capital of Bihar, because of its cold climate during the winter season.[9] Ranchi is also one of the oldest cities in Jharkhand. Jagannath Temple and Ratu Palace are some sights which witnessed the history of Ranchi.[10]\n" +
                    "\n" +
                    "Ranchi is rapidly growing its economy, and certain parks, special economic zones and industrial areas are being developed. Of late, new sectors and modern areas have been built for the city's development.[11] Ranchi is also nicknamed the 'City of Waterfalls'.", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Netarhat", "Netarhat is known for its sunrises and sunsets during the summer months.[6] It is located within forests which have varied flora and fauna.[citation needed]\n" +
                    "\n" +
                    "Netarhat has several places of tourist interests:\n" +
                    "\n" +
                    "Upper Ghaghri Falls is situated 4 km away from Netarhat.\n" +
                    "Lodh Falls is the highest waterfall of Jharkhand and 21st highest in India. This waterfall is situated at 70 km away from Netarhat and in the forest of Sal.\n" +
                    "Mahuadanr Wolf Sanctuary is the lone sanctuary in India made for the protection of wolves and mainly consists of Indian wolves.[7]\n" +
                    "Magnolia Point, It is 10 km away from Netarhat and is known for its sunset.\n" +
                    "Sunrise Point is situated in Netarhat and known for its sunrise at mornings.\n" +
                    "Lower Ghaghri Falls It is situated 10 km away from Netarhat and is known for its waterfall.[citation needed]\n" +
                    "Koel river View Point is 3 km from Netarhat.\n" +
                    "Suga Bandh Falls is situated at 70 km away from Netarhat and is a picnic spot for locals.\n" +
                    "Sadni Falls is 35 km from Netarhat.[3]\n" +
                    "Betla National Park is situated at 94 km away from the place and known among the first national parks in India to become a tiger reserve under Project Tiger (Palamu Tiger Reserve), 64 km away from Netarhat. It also houses two historic forts of Chero kings.\n" +
                    "Netarhat Residential School, boarding school and one of the few modern 'Gurukuls' left in India.\n" +
                    "Pear Orchards and Pine Forests are initiative of local Forest Department and they planted a lot of trees in the place.", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Sun Temple", "Konark Sun Temple is a 13th-century CE (year 1250) Sun temple at Konark about 35 kilometres (22 mi) northeast from Puri city on the coastline in Puri district, Odisha, India.[1][2] The temple is attributed to king Narasimhadeva I of the Eastern Ganga dynasty about 1250 CE.[3][4]\n" +
                    "\n" +
                    "Dedicated to the Hindu Sun God Surya, what remains of the temple complex has the appearance of a 100-foot (30 m) high chariot with immense wheels and horses, all carved from stone. Once over 200 feet (61 m) high,[1][5] much of the temple is now in ruins, in particular the large shikara tower over the sanctuary; at one time this rose much higher than the mandapa that remains. The structures and elements that have survived are famed for their intricate artwork, iconography, and themes, including erotic kama and mithuna scenes. Also called the Surya Devalaya, it is a classic illustration of the Odisha style of Architecture or Kalinga architecture.[1][6]\n" +
                    "\n" +
                    "The cause of the destruction of the Konark temple is unclear and still remains a source of controversy.[7] Theories range from natural damage to deliberate destruction of the temple in the course of being sacked several times by Muslim armies between the 15th and 17th centuries.[1][7] This temple was called the \"Black Pagoda\" in European sailor accounts as early as 1676 because it looked like a great tiered tower which appeared black.[6][8] Similarly, the Jagannath Temple in Puri was called the \"White Pagoda\". Both temples served as important landmarks for sailors in the Bay of Bengal.[9][10] The temple that exists today was partially restored by the conservation efforts of British India-era archaeological teams. Declared a UNESCO world heritage site in 1984,[1][2] it remains a major pilgrimage site for Hindus, who gather here every year for the Chandrabhaga Mela around the month of February.[6]", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Baidynath Dham", "Vaidyanatha Jyotirlinga temple, also known as Baba Baidyanath dham and Baidyanath dham is one of the twelve Jyotirlingas, the most sacred abodes of Shiva. It is located in Deoghar in the Santhal Parganas division of the state of Jharkhand, India. It is a temple complex consisting of the main temple of Baba Baidyanath, where the Jyotirlinga is installed, and 21 other temples.[2]\n" +
                    "\n" +
                    "According to Hindu beliefs, the demon king Ravana worshipped Shiva at the current site of the temple to get the boons that he later used to wreak havoc in the world. Ravana offered his ten heads one after another to Shiva as a sacrifice. Pleased with this, Shiva descended to cure Ravana who was injured. As he acted as a doctor, he is referred to as Vaidhya (\"doctor\"). The temple derives its name from this aspect of Shiva.\n" +
                    "\n" +
                    "Kanwar Yatra (Devanagari: कांवड़ यात्रा) is an annual pilgrimage of devotees of Shiva, known as Kānvarias (कांवड़िया) or \"Bhole\" (भोले) to Hindu pilgrimage places of Sultanganj in Bihar to fetch holy waters of Ganges River. Millions of participants gather sacred water from the Ganga and carry it across hundreds of miles to dispense as offerings in Baidyanath Temple in Jharkhand.", ""));
        } else if (state_name.equals("Karnataka")) {
            famousPlacesModelList.add(new FamousPlacesModel("Bengaluru", "Bangalore (/bæŋɡəˈlɔːr/), officially Bengaluru (Kannada pronunciation: [ˈbeŋgɐɭuːɾu] (listen)), is the capital and largest city of the Indian state of Karnataka. It has a population of more than 8 million and a metropolitan population of around 11 million, making it the third most populous city and fifth most populous urban agglomeration in India, as well as the largest city in South India, and the 27th largest city in the world.[12] Located on the Deccan Plateau, at a height of over 900 m (3,000 ft) above sea level, Bangalore has a pleasant climate throughout the year, with its parks and green spaces earning it the reputation as the \"Garden City\" of India.[13] Its elevation is the highest among the major cities of India.[14] An aerospace, heavy engineering and electronics hub since the 1960s, Bangalore is widely regarded as the \"Silicon Valley of India\" because of its role as the nation's leading information technology (IT) exporter.[1][13] In the Ease of Living Index 2020 (published by the Ministry of Housing and Urban Affairs), it was ranked the most livable Indian city with a population of over a million. [15] It also ranks among the highest Indian cities in terms of global livability rankings as well.", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Mysore Palace", "The Mysore Palace, also known as Amba Vilas Palace, is a historical palace and a royal residence (house). It is located in Mysore, Karnataka. It used to be the official residence of the Wadiyar dynasty and the seat of the Kingdom of Mysore. The palace is in the centre of Mysore, and faces the Chamundi Hills eastward. Mysore is commonly described as the 'City of Palaces', and there are seven palaces including this one. However, the Mysore Palace refers specifically to the one within the new fort.\n" +
                    "\n" +
                    "The land on which the palace now stands was originally known as mysuru (literally, \"citadel\"). Yaduraya built the first palace inside the Old Fort in the 14th century, which was set ablaze and reconstructed multiple times. The Old Fort was built of wood and thus easily caught fire, while the current fort was built of stone, bricks and wood. The current structure was constructed between 1897 and 1912, after the Old Palace burnt down, the current structure is also known as the New Fort. Mysore Palace is one of the most famous tourist attractions in India, after the Taj Mahal, with more than six million annual visitors.[1]", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Lalbagh", "Lalbagh Botanical Garden or simply Lalbagh (lit. 'red garden'), is an botanical garden in Bangalore, India, with an over 200-year history. First planned and laid out during the dalavaiship of Hyder Ali and later managed under numerous British Superintendents before Indian Independence. It was responsible for the introduction and propagation of numerous ornamental plants as well as those of economic value. It also served a social function as a park and recreational space, with a central glass house dating from 1890 which was used for flower shows. In modern times it hosts two flower shows coinciding with the week of Republic Day (26 January) and Independence Day (15 August). As an urban green space along with Cubbon Park, it is also home to numerous wild species of birds and other wildlife. The garden also has a lake adjoining a large rock on which a watchtower had been constructed during the reign of Kempegowda II.", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Bandipur National Park", "Bandipur National Park is located between 75° 12’ 17\" E to 76° 51’ 32\" E and 11° 35’ 34\" N to 11° 57’ 02\" N where the Deccan Plateau meets the Western Ghats, and the altitude of the park ranges from 680 meters (2,230 ft) to 1,454 meters (4,770 ft). As a result, the park has a variety of biomes including dry deciduous forests, moist deciduous forests and shrublands. The wide range of habitats help support a diverse range of organisms. The park is flanked by the Kabini river in the north and the Moyar river in the south. The Nugu river runs through the park. The highest point in the park is on a hill called Himavad Gopalaswamy Betta, where there is a Hindu temple at the summit. Bandipur has typical tropical climate with distinct wet and dry seasons. The dry and hot period usually begins in early March and can last till the arrival of the monsoon rains in June.", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Hampi", "Hampi or Hampe, also referred to as the Group of Monuments at Hampi, is a UNESCO World Heritage Site located in Hampi town, Vijayanagara district, east-central Karnataka, India.[2]\n" +
                    "\n" +
                    "Hampi was the capital of the Vijayanagara Empire in the 14th century.[3] It was a fortified city. Chronicles left by Persian and European travellers, particularly the Portuguese, say that Hampi was a prosperous, wealthy and grand city near the Tungabhadra River, with numerous temples, farms and trading markets. By 1500 CE, Hampi-Vijayanagara was the world's second-largest medieval-era city after Beijing, and probably India's richest at that time, attracting traders from Persia and Portugal.[4][5] The Vijayanagara Empire was defeated by a coalition of Muslim sultanates; its capital was conquered, pillaged and destroyed by sultanate armies in 1565, after which Hampi remained in ruins.[3][6][7]\n" +
                    "\n" +
                    "Located in Karnataka near the modern-era city of Hosapete, Hampi's ruins are spread over 4,100 hectares (16 sq mi) and it has been described by UNESCO as an \"austere, grandiose site\" of more than 1,600 surviving remains of the last great Hindu kingdom in South India that includes \"forts, riverside features, royal and sacred complexes, temples, shrines, pillared halls, mandapas, memorial structures, water structures and others\".[8]\n" +
                    "\n" +
                    "Hampi predates the Vijayanagara Empire, it is mentioned in the Ramayana and the Puranas of Hinduism as Pampaa Devi Tirtha Kshetra.[3][9] Hampi continues to be an important religious centre, housing the Virupaksha Temple, an active Adi Shankara-linked monastery and various monuments belonging to the old city.", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Coorg", "Kodagu (also known by its former name Coorg) is an administrative district in the Karnataka state of India. Before 1956, it was an administratively separate Coorg State,[3] at which point it was merged into an enlarged Mysore State.[4]\n" +
                    "\n" +
                    "It occupies an area of 4,102 square kilometres (1,584 sq mi) in the Western Ghats of southwestern Karnataka. In 2001 its population was 548,561, 13.74% of which resided in the district's urban centre, making it the least populous of the 31 districts in Karnataka.\n" +
                    "\n" +
                    "The nearest railway stations are Mysore Junction, located around 95 km (59 mi) away, Thalassery, and Kannur, the latter two located in Kerala at a distance of about 79 km (49 mi). The nearest airports are Kannur International Airport in Kerala (90 km (56 mi) from Madikeri) and Mangalore International Airport (144 km (89 mi) from Madikeri).", ""));
        } else if (state_name.equals("Kerala")) {
            famousPlacesModelList.add(new FamousPlacesModel("Munnar", "The region has been inhabited by hunter-gatherer tribals like the Malayarayan and Muthuvan for thousands of years.[6] Tradition states that Colonel Arthur Wellesley, later the Duke of Wellington, was the first British person to pass through Munnar during Tippu Sultan's campaign in Travancore, but this is unsubstantiated. The first survey of the terrain was undertaken by Benjamin Swayne Ward in 1816–1817, who followed the Periyar into the Western Ghats and established a camp at the confluence of three rivers, from which the name of Munnar is derived.[7]\n" +
                    "\n" +
                    "It was to be nearly 50 years later that Sir Charles Trevelyan, Governor of Madras, instructed Col. Douglas Hamilton to explore the hill country in the western part of the Madras Presidency, requesting special advice on the feasibility of establishing sanatoria for the British in the South and of developing revenue- earning projects without endangering the environment, as had happened in Ceylon where coffee had destroyed not only the rain forest but also paddy cultivation in the north-central rice bowl of ancient Ceylon. Hamilton climbed throughout the Ghats in Munnar region. 15 years later, John Daniel Munro noted that much of Munnar's land was suitable for coffee plantations. Munro, Henry Turn and his half-brother AW Turner obtained ownership of the Cardamom Hills from the Raja of Travancore and began clearing forest around Devikulam in 1879. Soon many other Europeans began establishing tea plantations in the area throughout the 1880s. Early plantations had few facilities and were mainly huts of straw. Most labourers on the tea estates were Dalits from present-day Tamil Nadu.[8][6]", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Alappuzha", "Alappuzha or Alleppey (Malayalam: [ɐːlɐpːuɻɐ] (listen)) is the administrative headquarters of Alappuzha district in state of Kerala, India. The Backwaters of Alappuzha are one of the most popular tourist attractions in India which attracts millions of domestic and international tourists.[3]\n" +
                    "\n" +
                    "Alleppey is a city and a municipality in Kerala with an urban population of 174,164[4] and ranks third among the districts in literacy rate in the state. In 2016, the Centre for Science and Environment rated Alappuzha as the cleanest town in India.[5] Alappuzha is considered to be the oldest planned city in this region and the lighthouse built on the coast of the city is the first of its kind along the Laccadive Sea coast.[6]\n" +
                    "\n" +
                    "The city is 55 km from Kochi and 155 km north of Thiruvananthapuram.[7] A town with canals, backwaters, beaches, and lagoons, Alappuzha was described by George Curzon, Viceroy of India at the start of the 20th century, as the \"Venice of the East.\"[8] Hence, it is known as the \"Venetian Capital\" of Kerala.\n" +
                    "\n" +
                    "It is an important tourist destination in India.[9] It connects Kumarakom and Cochin to the North and Kollam to the South. It is also the access point for the annual Nehru Trophy Boat Race, held on the Punnamada Lake, near Alappuzha, on the second Saturday of August every year. This is amongst the most popular and competitive boat races in India.[10]\n" +
                    "\n" +
                    "Alappuzha was home to the Punnapra-Vayalar uprising against the Separate American Model independent Travancore proposal and also the revolt against the Feudal raj. Over 200 Communist party members were killed by the army of the Diwan at Punnapra.[11] Coir is the most important commodity manufactured in Alappuzha.[12] The Coir Board was established by the Central Government under the provisions of the Coir Industry Act, 1955. A Central Coir Research Institute is located at Kalavoor.", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Kochi", "Kochi ([koˈtːʃi ] (listen)), also known as Cochin (/ˈkoʊtʃɪn/ KOH-chin)[9] (the official name until 1996) is a major port city on the Malabar Coast of India bordering the Laccadive Sea, which is a part of the Arabian Sea. It is part of the district of Ernakulam in the state of Kerala and is commonly referred to as Ernakulam. Kochi is the most densely populated city in Kerala. As of 2011, it has a corporation limit population of 677,381[4] within an area of 94.88 km2 and a total urban population of more than of 2.1 million within an area of 440 km2, making it the largest and the most populous metropolitan area in Kerala. Kochi city is also part of the Greater Cochin region[10][11] and is classified as a Tier-II city by the Government of India. The civic body that governs the city is the Kochi Municipal Corporation, which was constituted in the year 1967, and the statutory bodies that oversee its development are the Greater Cochin Development Authority[12] (GCDA) and the Goshree Islands Development Authority (GIDA).[13] The current metropolitan limits of Kochi include the mainland Ernakulam, Fort Kochi, the suburbs of Edapally, Kalamassery, Aluva and Kakkanad to the northeast; Tripunithura to the southeast; and a group of islands closely scattered in the Vembanad Lake.", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Allepey Backwaters", "The Kerala backwaters are a network of brackish lagoons and canals lying parallel to the Arabian Sea of the Malabar coast of Kerala state in south-western India. It also includes interconnected lakes, rivers, and inlets, a labyrinthine system formed by more than 900 km (560 mi) of waterways, and sometimes compared to bayous.[3] The network includes five large lakes linked by canals, both man made and natural, fed by 38 rivers, and extending virtually half the length of Kerala state. The backwaters were formed by the action of waves and shore currents creating low barrier islands across the mouths of the many rivers flowing down from the Western Ghats range. In the midst of this landscape there are a number of towns and cities, which serve as the starting and end points of backwater cruises.[4] There are 34 backwaters in Kerala.[5] Out of it, 27 are located either closer to Arabian Sea or parallel to the sea.[5] The remaining 7 are inland navigation routes.[5]", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Kovalam", "Kovalam has three beaches separated by rocky outcroppings in its 17 km coastline, the three together form the crescent of the Kovalam beach.[4]\n" +
                    "\n" +
                    "Lighthouse Beach\n" +
                    "The southernmost beach, the Lighthouse Beach, is the one most frequented by tourists. It got its name due to the old Vizhinjam Lighthouse located on top of the Kurumkal hillock, 35 metres high. The lighthouse is built using stones, is colored in red and white bands and stands at a height of 118 feet (36 m).[5] [6]\n" +
                    "Hawah Beach\n" +
                    "Eve’s Beach, more commonly known as Hawa Beach, ranks second, in the early day, is a beehive of activities with fishermen setting out for sea. It consists of a high rock promontory and a bay.\n" +
                    "Samudra Beach\n" +
                    "A large promontory separates this part from the southern side. The local fishermen ply their trade on this part.\n" +
                    "Detour past Kovalam junction to land on Samudra Beach which is to the north of Ashoka Beach. One has the option to walk along the sea-wall too, where the sea can be sighted above the rocks.\n" +
                    "\n" +
                    "Shallow waters stretching for hundreds of metres are ideal for swimming. The beaches have steep palm covered headlands and are lined with shops that offer a variety of goods and services.[7]", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Athirappilly Waterfalls", "Athirappilly Falls, is situated in Athirappilly Panchayat in Chalakudy Taluk of Thrissur District in Kerala, India on the Chalakudy River, which originates from the upper reaches of the Western Ghats at the entrance to the Sholayar ranges. It is the largest waterfall in Kerala, which stands tall at 81.5 feet. Just a short drive from Athirappilly to the Vazhachal falls, which is close to dense green forests that are home to many endangered and endemic species of flora and fauna.\n" +
                    "\n" +
                    "There is another waterfall on the way from Athirappilly to Vazhachal Falls, in close proximity to the road, which is locally called \"Charpa Falls\". Athirappilly Falls is the largest waterfall in Kerala and is nicknamed \"The Niagara of South India\".[1]\n" +
                    "\n" +
                    "Controversy about a state-proposed hydroelectric dam on the Chalakudy River above the waterfalls began in the 1990s and continued through 2017.", ""));
        } else if (state_name.equals("Madhya Pradesh")) {
            famousPlacesModelList.add(new FamousPlacesModel("Karera Wildlife Sanctuary", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Ken Gharial Sanctuary", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Bandhavgarh National Park", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Kanha National Park", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Gwalior Gharana", "", ""));
        } else if (state_name.equals("Maharashtra")) {
            famousPlacesModelList.add(new FamousPlacesModel("Gateway of India", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Ajanta Caves", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Chhatrapati Shivaji Maharaj Terminus", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Ellora Caves", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Elephanta Caves", "", ""));
        } else if (state_name.equals("Manipur")) {
            famousPlacesModelList.add(new FamousPlacesModel("Loktak Lake", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Kangla Fort", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Keibul Lamjao National Park", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Moirang", "", ""));
        } else if (state_name.equals("Meghalaya")) {
            famousPlacesModelList.add(new FamousPlacesModel("Elephant Falls", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Umiam Lake", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Cherrapunji", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Mawlynnong village", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Nohkalikai Falls", "", ""));
        } else if (state_name.equals("Mizoram")) {
            famousPlacesModelList.add(new FamousPlacesModel("Reiek Heritage Village", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Durtlang Hills", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Murlen National Park", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Khawnglung Wildlife Sanctuary", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Tam Dil", "", ""));
        } else if (state_name.equals("Nagaland")) {
            famousPlacesModelList.add(new FamousPlacesModel("Dimapur", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Kohima War Cemetery", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Mokokchung", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Khonoma village", "", ""));
        } else if (state_name.equals("Odisha")) {
            famousPlacesModelList.add(new FamousPlacesModel("Puri", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Konark Sun temple", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Chilika lake", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Jagannath Temple", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Nandankanan Zoological Park", "", ""));
        } else if (state_name.equals("Punjab")) {
            famousPlacesModelList.add(new FamousPlacesModel("Jallianwala Bagh", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Golden Temple", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Wagah Border", "", ""));
        } else if (state_name.equals("Rajasthan")) {
            famousPlacesModelList.add(new FamousPlacesModel("Amber Palace", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Hawa Mahal", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("City Palace of Udaipur", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Jodhpur", "", ""));
        } else if (state_name.equals("Sikkim")) {
            famousPlacesModelList.add(new FamousPlacesModel("Nathula Pass", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Yumthang Valley", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Khangchendzonga National Park", "", ""));
        } else if (state_name.equals("Tamil Nadu")) {
            famousPlacesModelList.add(new FamousPlacesModel("Mahabalipuram", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Madurai", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Marina Beach", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Ooty", "", ""));
        } else if (state_name.equals("Telangana")) {
            famousPlacesModelList.add(new FamousPlacesModel("Charminar", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Golconda Fort", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Karimnagar", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Warangal", "", ""));
        } else if (state_name.equals("Tripura")) {
            famousPlacesModelList.add(new FamousPlacesModel("Tripura Sundari Temple", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Kailashahar", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Unakoti", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Neermahal Palace", "", ""));
        } else if (state_name.equals("Uttar Pradesh")) {
            famousPlacesModelList.add(new FamousPlacesModel("Taj Mahal", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Agra Fort", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Kashi Vishwanath Temple", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Varanasi", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Ganges River", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Mathura", "", ""));
        } else if (state_name.equals("Uttarakhand")) {
            famousPlacesModelList.add(new FamousPlacesModel("Haridwar", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Nainital", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Rishikesh", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Mussoorie ", "", ""));
        } else if (state_name.equals("West Bengal")) {
            famousPlacesModelList.add(new FamousPlacesModel("Howrah bridge", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Darjeeling", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Kalimpong", "", ""));
            famousPlacesModelList.add(new FamousPlacesModel("Sunderban National Park", "", ""));
        }
        recyclerView = findViewById(R.id.Famous_Places_rv);
        recyclerView.setLayoutManager(new LinearLayoutManager(this));
        famousPlacesAdapter = new FamousPlacesAdapter();
        famousPlacesAdapter.passDataToAdapter(famousPlacesModelList);
        recyclerView.setAdapter(famousPlacesAdapter);
    }
}
